
version: '3.8'
services:
  db:
    image: gvenzl/oracle-xe
    container_name: db
    environment:
      - ORACLE_PASSWORD=root
    ports:
      - "1521:1521"
      - "5000:5000"
    networks:
      - my-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network
    volumes:
      - web_data:/app/data/csv

networks:
  my-network:
    driver: bridge

volumes:
  web_data:
      driver: local





